version: "3"

services:
  promtail:
    image: grafana/promtail:1.6.1
    container_name: promtail
    user: "${PUID}:${PGID}"
    command: -config.file=/config/promtail-config.yml
    user: "${PUID}:${PGID}"
    volumes:
      - ./promtail/config:/config:ro
      - ./promtail/data:/promtail
      - /var/log:/var/log
    restart: unless-stopped

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    user: "${PUID}:${PGID}"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.service=cadvisor"
      - "traefik.http.routers.cadvisor.tls=true"
      - "traefik.http.routers.cadvisor.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.cadvisor.entrypoints=websecure"
      - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"
      # Basic auth
      - "traefik.http.routers.cadvisor.middlewares=cadvisor-auth"
      - "traefik.http.middlewares.cadvisor-auth.basicauth.users=$CADVISOR_USER_PASSWORD"
    networks:
      - prometheus
      - web_proxy

  node-exporter:
    image: bitnami/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    networks:
      - prometheus

networks:
  web_proxy:
    external:
      name: web_proxy