server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: https://loki.example.com/loki/api/v1/push
    basic_auth:
      username: user
      password: password

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: servername
          __path__: /var/log/*log
        